spring:
  application:
    name: status-loader
  profiles:
    active: status_loader
  config:
    import: optional:configserver:${SPRING_CONFIG_IMPORT_URI:http://localhost:8888/}
  cloud:
    config:
      name: config-client
      username: devkhoa
      password: '{cipher}8997f5ba338c140673bd23e3579f84871b47cfffee03da3de6167acdaed8fdb60660754222b7b8f218da17f29f490809'

encrypt:
  key: ${ENCRYPT_KEY}

#logging:
#  level:
#    ROOT: INFO
#    org.apache.kafka: DEBUG