server:
  port: 8888
logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KhoaNguyen2907/status-collector-config-repository.git
          clone-on-start: true
          default-label: master
          username: ndkhoalk97@gmail.com
          #this personal github password may be expired
          password: '{cipher}8bba07203fca36089347fc570a8acf586022a9625757945afac9b6b1c3ede2634cbe353f1fdfb67ff858532e4dda53c572ef79ad9dae8175f17d21975d394f01a2e68675c321c0708644338e8123b97e02d348958c7a55d274e044c2bd07083c2d375b213685af4df017b31a2501dcc2'
    fail-fast: true

  security:
    user:
      name: devkhoa
      password: '{cipher}8997f5ba338c140673bd23e3579f84871b47cfffee03da3de6167acdaed8fdb60660754222b7b8f218da17f29f490809'
encrypt:
  key: ${ENCRYPT_KEY}
