server:
  port: 8888
logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KhoaNguyen2907/status-collector-config-repository.git
          clone-on-start: true
          default-label: master
          username: ndkhoalk97@gmail.com
          password: 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
    fail-fast: true

  security:
    user:
      name: devkhoa
      password: devkhoa_password
